---
site_name: "Waldiez!"
site_description: "Waldiez."
site_url: https://waldiez.github.io/py/
repo_name: waldiez/py
repo_url: https://github.com/waldiez/py.git
edit_uri_template: 'blob/main/docs/{path}'
edit_uri: 'blob/main/docs/'
copyright: "Copyright &copy; 2024 Waldiez"
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: white
      accent: blue
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      accent: blue
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    # - announce.dismiss
    # - content.action.edit
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    # - navigation.tabs
    - navigation.top
    - navigation.tracking
    - toc.follow
  icon:
    repo: material/git
  logo: static/images/logo.svg
  favicon: static/favicon.ico
  include_sidebar: false

markdown_extensions:
  - toc:
      permalink: true
      baselevel: 2
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition
  - codehilite
  - extra
  - mdx_truly_sane_lists
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          # yamllint disable
          format: !!python/name:pymdownx.superfences.fence_code_format ''
          # yamllint enable
  - pymdownx.tabbed:
      alternate_style: true
  - mdx_include:
      base_path: docs

plugins:
  - mkdocs-jupyter:
  - search:
      lang: en
  - minify_html
  - macros
  - autorefs
  - privacy
  - mkdocstrings:
      enabled: true
      default_handler: python
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
          selection:
            new_path_syntax: true
          paths: [waldiez]
          options:
            filters:
              - "!^_"
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            ignore_init_summary: true
            merge_init_into_class: true
            docstring_style: numpy
            show_submodules: true
            show_root_heading: false
            show_signature_annotations: true
            signature_crossrefs: true
            show_source: true
            group_by_category: false
            show_category_heading: true

nav:
  - Waldiez!: index.md
  - Reference:
      - Models:
          - Model: models/model.md
          - Skill: models/skill.md
          - Agents:
              - Agents: models/agents/index.md
              - Agent: models/agents/agent.md
              - Assistant: models/agents/assistant.md
              - UserProxy: models/agents/user_proxy.md
              - GroupManager: models/agents/group_manager.md
              - RagUser: models/agents/rag_user.md
          - Chat: models/chat.md
          - Flow: models/flow.md
          - Common: models/common.md
      - Exporting:
          - Models: exporting/models.md
          - Skills: exporting/skills.md
          - Chats: exporting/chats.md
          - Agents: exporting/agents.md
          - Flow: exporting/flow.md
          - Utils: exporting/utils.md
      - Stream:
          - Server: stream/server.md
          - Consumer: stream/consumer.md
          - Provider: stream/provider.md
      - Waldie: waldie.md
      - WaldieRunner: runner.md
      - WaldieExporter: exporter.md
      - WaldieIOSstream: io_stream.md
