---
name: Build and push container images
# yamllint disable rule:truthy
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
    inputs:
      version_tag:
        description: "The version tag to build and push (e.g. v1.2.3 or latest)"
        required: true
        default: "latest"

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ vars.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Determine Docker Tag
        id: docker_tag
        run: |
          if  [[ "${{github.event_name}}" == 'push' ]]; then
            tag="${{ github.ref }}"
          else
            tag="${{ github.event.inputs.version_tag }}"
          fi
          echo "docker_tag=$tag" >> $GITHUB_OUTPUT

      - name: Build and push core
        uses: docker/build-push-action@v6
        with:
          platforms: |
            linux/amd64
            linux/arm64
          file: packages/core/python/Containerfile
          context: packages/core/python
          push: false
          tags: |
            waldiez/waldiez:${{ steps.docker_tag.outputs.docker_tag }}
            quay.io/waldiez/waldiez:${{ steps.docker_tag.outputs.docker_tag }}

      - name: Build and push jupyter
        # manually, after publishing waldiez_jupyter
        if: github.event_name == 'workflow_dispatch'
        uses: docker/build-push-action@v6
        with:
          platforms: |
            linux/amd64
            linux/arm64
          file: packages/jupyter/Containerfile
          context: packages/jupyter
          push: false
          tags: |
            waldiez/waldiez-jupyter:${{ steps.docker_tag.outputs.docker_tag }}
            quay.io/waldiez/waldiez-jupyter:${{ steps.docker_tag.outputs.docker_tag }}

      - name: Build and push studio
        # manually, after publishing waldiez_studio
        if: github.event_name == 'workflow_dispatch'
        uses: docker/build-push-action@v6
        with:
          platforms: |
            linux/amd64
            linux/arm64
          file: packages/studio/Containerfile
          context: packages/studio
          push: false
          tags: |
            waldiez/waldiez-studio:${{ steps.docker_tag.outputs.docker_tag }}
            quay.io/waldiez/waldiez-studio:${{ steps.docker_tag.outputs.docker_tag }}
