---
name: Build and push container images
# yamllint disable rule:truthy
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  contents: read
  packages: write

jobs:
  docker:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ vars.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build and push core
        uses: docker/build-push-action@v6
        with:
          platforms: |
            linux/amd64
            linux/arm64
          file: packages/core/python/Containerfile
          context: packages/core/python
          push: false
          tags: |
            waldiez/waldiez:${{ github.ref_type == 'tag' && github.ref_name || 'latest' }}
            quay.io/waldiez/waldiez:${{ github.ref_type == 'tag' && github.ref_name || 'latest' }}

      - name: Build and push jupyter
        uses: docker/build-push-action@v6
        with:
          platforms: |
            linux/amd64
            linux/arm64
          file: packages/jupyter/Containerfile
          context: packages/jupyter
          push: false
          tags: |
            waldiez/waldiez-jupyter:${{ github.ref_type == 'tag' && github.ref_name || 'latest' }}
            quay.io/waldiez/waldiez-jupyter:${{ github.ref_type == 'tag' && github.ref_name || 'latest' }}

      - name: Build and push studio
        uses: docker/build-push-action@v6
        with:
          platforms: |
            linux/amd64
            linux/arm64
          file: packages/studio/Containerfile
          context: packages/studio
          push: false
          tags: |
            waldiez/waldiez-studio:${{ github.ref_type == 'tag' && github.ref_name || 'latest' }}
            quay.io/waldiez/waldiez-studio:${{ github.ref_type == 'tag' && github.ref_name || 'latest' }}
