---
# WIP
name: Publish React package to NPM

# yamllint disable rule:truthy
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - monorepo

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  publish_waldiez_react:
      # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      if: github.event_name == 'push' && github.ref_name == 'monorepo'
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            submodules: "recursive"

        - name: Setup bun
          uses: oven-sh/setup-bun@v2

        - name: Install dependencies
          run: |
            cd packages/core/react
            bun install
        - name: Build
          run: |
            cd packages/core/react
            bun build:lib

        - name: Store the distribution packages
          uses: actions/upload-artifact@v4
          with:
            name: waldiez-react-package-distribution
            path: packages/core/react/dist/

        # - name: Publish to NPM
        #   if: success()
        #   env:
        #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        #   run: bun publish
