---
# WIP
name: Publish Python package to PyPI

# yamllint disable rule:truthy
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - monorepo

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  publish_waldiez_python:
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    # test in monorepo first
    if: github.event_name == 'push' && github.ref_name == 'monorepo'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: python -m pip install --break-system-packages build twine

      - name: Build 🏗️
        run: |
          cd packages/core/python
          python -m build --sdist --wheel --outdir dist/
          python -m twine check dist/*

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: waldiez-python-package-distribution
          path: packages/core/python/dist/
