---
# WIP
name: "Publish Waldiez studio to PyPi"

# yamllint disable rule:truthy
on:
  workflow_run:
    workflows:
      - "Publish React package to NPM"
      - "Publish Python package to PyPI"
    branches:
      - monorepo
    types:
      - completed

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  publish_waldiez_studio:
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    if: github.event_name == 'push' && github.ref_name == 'monorepo'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --break-system-packages build twine

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Download artifact from python package
        uses: actions/download-artifact@v4
        with:
          name: waldiez-python-package-distribution
          path: packages/core/python/dist/

      - name: Download artifact from react package
        uses: actions/download-artifact@v4
        with:
          name: waldeiz-react-package-distribution
          path: packages/core/react/dist/

      - name: Get the new version of the package
        run: |
          sudo update && sudo apt install -y jq
          mkdir -p .local
          cat package.json | jq -r '.version' > .local/VERSION
          cd packages/jupyter
          mkdir -p .local
          mv ../../.local/VERSION .local/VERSION
          cat package.json | jq -r '.version' > .local/VERSION

      - name: Set the new @waldiez/react to the path of the artifact
        run: |
          cd packages/studio
          bun remove @waldiez/react
          bun add @waldiez/react@file:../../react/dist/waldiez-react-$(cat .local/VERSION).tgz
          bun install

      - name: Build the frontend part of the extension
        run: |
          cd packages/studio
          bun run build

      - name: Build the python part of the extension
        run: |
          cd packages/studio
          python -m build --sdist --wheel --outdir dist/
          python -m twine check dist/*
