---
name: Lint and Test

# yamllint disable rule:truthy
on:
  push:
    branches:
      - main
      - dev
      - monorepo
jobs:
  test:
    runs-on:
      ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: patch package.json
        run: |
          bun install
          bun run ci:patch

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install corepack and yarn
        run: |
          corepack enable
          yarn set version stable

      - name: Rollback package.json
        run: |
          bun run ci:rollback

      - name: Install dependencies
        run: |
          bun install
          bun run requirements:ts
          pip install --upgrade pip uv
          uv sync --all-packages

      - name: Run Tests
        run: bun run test
